-- MySQL Script generated by MySQL Workbench
-- sáb 04 dez 2021 11:12:54
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_bluebank
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_bluebank
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_bluebank` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `db_bluebank` ;

-- -----------------------------------------------------
-- Table `db_bluebank`.`tb_contas_corrente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_bluebank`.`tb_contas_corrente` (
  `conta` BIGINT NOT NULL AUTO_INCREMENT,
  `agencia` VARCHAR(255) NULL DEFAULT NULL,
  `data_de_abertura` DATE NULL DEFAULT NULL,
  `data_de_encerramento` DATE NULL DEFAULT NULL,
  `saldo_da_conta` DOUBLE NOT NULL,
  PRIMARY KEY (`conta`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_bluebank`.`tb_enderecos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_bluebank`.`tb_enderecos` (
  `id_endereco` BIGINT NOT NULL AUTO_INCREMENT,
  `bairro` VARCHAR(255) NULL DEFAULT NULL,
  `cep` VARCHAR(255) NULL DEFAULT NULL,
  `cidade` VARCHAR(255) NULL DEFAULT NULL,
  `complemento` VARCHAR(255) NOT NULL,
  `estado` VARCHAR(255) NOT NULL,
  `logradouro` VARCHAR(255) NULL DEFAULT NULL,
  `numero` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_endereco`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_bluebank`.`tb_clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_bluebank`.`tb_clientes` (
  `id_cliente` BIGINT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `nome` VARCHAR(255) NULL DEFAULT NULL,
  `renda` DOUBLE NULL DEFAULT NULL,
  `telefone` VARCHAR(20) NULL DEFAULT NULL,
  `tipo_cliente` VARCHAR(255) NULL DEFAULT NULL,
  `conta` BIGINT NULL DEFAULT NULL,
  `id_endereco` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id_cliente`),
  UNIQUE INDEX `UK_gi4dq7wt46i38i0iu4rukcosa` (`conta` ASC) VISIBLE,
  UNIQUE INDEX `UK_7uin55rct5vvmbnmgxmw5lcx7` (`id_endereco` ASC) VISIBLE,
  CONSTRAINT `FK41g5ho8f3hgx781ycw64gkp2e`
    FOREIGN KEY (`conta`)
    REFERENCES `db_bluebank`.`tb_contas_corrente` (`conta`),
  CONSTRAINT `FKd4al1oogaja5ywt0782w3fjvr`
    FOREIGN KEY (`id_endereco`)
    REFERENCES `db_bluebank`.`tb_enderecos` (`id_endereco`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_bluebank`.`tb_transacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_bluebank`.`tb_transacoes` (
  `numero_da_transacao` BIGINT NOT NULL AUTO_INCREMENT,
  `data_da_transacao` DATETIME(6) NULL DEFAULT NULL,
  `tipo_de_transacao` VARCHAR(255) NULL DEFAULT NULL,
  `valor_da_transacao` DOUBLE NULL DEFAULT NULL,
  `conta_de_destino` BIGINT NULL DEFAULT NULL,
  `conta_de_origem` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`numero_da_transacao`),
  INDEX `FKrocnfokt0tpavrvv6qoeyda0p` (`conta_de_destino` ASC) VISIBLE,
  INDEX `FKwgk2a95mwmafra6bjwduvxx5` (`conta_de_origem` ASC) VISIBLE,
  CONSTRAINT `FKrocnfokt0tpavrvv6qoeyda0p`
    FOREIGN KEY (`conta_de_destino`)
    REFERENCES `db_bluebank`.`tb_contas_corrente` (`conta`),
  CONSTRAINT `FKwgk2a95mwmafra6bjwduvxx5`
    FOREIGN KEY (`conta_de_origem`)
    REFERENCES `db_bluebank`.`tb_contas_corrente` (`conta`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


INSERT INTO tb_clientes (email, nome, renda, telefone, tipo_cliente)
VALUES
    ( 'joão@bluebank.com.br', 'João Pedro', 7500, '11 99992020', 'PESSOAFISICA'),
    ( 'leonadro@bluebank.com.br', 'Leandro Barros', 7500, '11 940002020', 'PESSOAFISICA'),
    ( 'luiz@bluebank.com.br', 'Luiz Nascimento', 7500, '11 94502020', 'PESSOAFISICA'),
    ( 'marcel@bluebank.com.br', 'Marcel Pinotti', 7500, '11 99002020', 'PESSOAFISICA'),
    ('pietracarlacosta@digitalsj.com.br', 'Pietra Carla Costa', 250000,'(94) 3535-6491','PESSOAJURIDICA'),
	('lorenarenatacastro@fertility.com.br','Lorena Renata Castro', 250000, '(22) 2959-3858','PESSOAJURIDICA'),
	('estherjulianaclarafigueiredo-88@splicenet.com.br', 'Esther Juliana Clara Figueiredo', 250000,'(17) 99662-2216','PESSOAJURIDICA'),
	('marcosvinicius-92@latapack.com.br', 'Marcos Vinicius Anderson da Mota', 250000, '(33) 98851-8154','PESSOAJURIDICA');
   

INSERT INTO tb_enderecos (id_endereco, bairro, cep, cidade, complemento, estado, logradouro, numero)
VALUES 
	(1, 'Centro', '39853-000', 'Belo Horizonte', 'Apto 5', 'MG', 'Rua A', 69),
    (2, 'Realengo', '21710-261', 'Rio de Janeiro', 'CS 1', 'RJ', 'Rua B', 402),
    (3, 'Centro', '04616-010', 'São Paulo', 'CS 3', 'SP', 'Rua C', 238),
    (4, 'Vila Bela', '03102-000', 'São Paulo', 'Apartamento 87', 'SP', 'Rua D', 68),
    (5,'Nova Marabá','68506-100','Marabá','CASA 2','PA','Quadra Dez',95),
    (6,'Nova Friburgo','28630-443','São Geraldo','APT 1','RJ','Rua Crésio Coelho Caetano',171),
    (7,'Residencial Acapulco','15804-401','Catanduva','GALPAO','SP','Avenida das Colinas',893),
    (8,'Nossa Senhora Aparecida','35303-011','Caratinga','ANDAR 5 APT 2','MG','Rua Francisco Florentino da Costa',85);
      
      
INSERT INTO tb_contas_corrente (conta, data_de_abertura, saldo_da_conta, agencia)
VALUES 
(1, '2021-11-27', 10000, 'AGENCIA3'),
(2, '2021-11-27', 10000, 'AGENCIA2'),
(3, '2021-11-27', 10000, 'AGENCIA2'),
(4, '2021-11-27', 10000, 'AGENCIA3'),
(5, '2021-11-27', 10000, 'AGENCIA2'),
(6, '2021-11-27', 10000, 'AGENCIA1'),
(7, '2021-11-27', 10000, 'AGENCIA2'),
(8, '2021-11-27', 10000, 'AGENCIA1');
    

UPDATE tb_clientes SET conta = 1, id_endereco = 1 WHERE (id_cliente = 1);
UPDATE tb_clientes SET conta = 2, id_endereco = 2 WHERE (id_cliente = 2);
UPDATE tb_clientes SET conta = 3, id_endereco = 3 WHERE (id_cliente = 3);
UPDATE tb_clientes SET conta = 4, id_endereco = 4 WHERE (id_cliente = 4);
UPDATE tb_clientes SET conta = 5, id_endereco = 5 WHERE (id_cliente = 5);
UPDATE tb_clientes SET conta = 6, id_endereco = 6 WHERE (id_cliente = 6);
UPDATE tb_clientes SET conta = 7, id_endereco = 7 WHERE (id_cliente = 7);
UPDATE tb_clientes SET conta = 8, id_endereco = 8 WHERE (id_cliente = 8);




